name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv and set Python 3.10
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.10"
          version: "0.10.9"
          enable-cache: true

      - name: Build project for distribution
        run: uv build

      - name: Check Version
        id: check-version
        run: |
          if ! [[ "$(uv version --short)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "prerelease=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: ${{ steps.check-version.outputs.prerelease == 'true' }}
          allowUpdates: true

      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish --check-url https://pypi.org/simple
      - name: Prune uv cache
        run: uv cache prune --ci
